### ISSUE TITLE
获取预授权码问题

### ISSUE THREAD

**Issue by cococa** [yydzxz/ByteDance-Open-Demo#9]
```
@GetMapping("/goto_auth_url")
    public void gotoPreAuthUrl(HttpServletRequest request, HttpServletResponse response){
        String host = request.getHeader("host");
        String scheme = request.getScheme();
        String url = scheme + "://"+host+"/bytedance/v2/auth/jump";
        GetPreAuthCodeRequest getPreAuthCodeRequest = new GetPreAuthCodeRequest();
        getPreAuthCodeRequest.setShareAmount(10);
        getPreAuthCodeRequest.setShareRatio(10);
        try {
            url = byteDanceOpenService.getByteDanceOpenV2ComponentService().getPreAuthUrl(url, getPreAuthCodeRequest);
            // 添加来源，解决302跳转来源丢失的问题
            response.addHeader("Referer", scheme + "://"+host);
            response.sendRedirect(url);
        } catch (ByteDanceErrorException | IOException e) {
            log.error("gotoPreAuthUrl", e);
            throw new RuntimeException(e);
        }
    }

```

https://partner.open-douyin.com/docs/resource/zh-CN/thirdparty/API/smallprogram/authorization/preauthcode
上面是demo 中的代码，但是查看了文档，发现参数是pre_auth_code_type app_name 这些，确定没搞错吗？还是抖音的接口变更了。

**Comment by yydzxz** [comment]
> ```
> @GetMapping("/goto_auth_url")
>     public void gotoPreAuthUrl(HttpServletRequest request, HttpServletResponse response){
>         String host = request.getHeader("host");
>         String scheme = request.getScheme();
>         String url = scheme + "://"+host+"/bytedance/v2/auth/jump";
>         GetPreAuthCodeRequest getPreAuthCodeRequest = new GetPreAuthCodeRequest();
>         getPreAuthCodeRequest.setShareAmount(10);
>         getPreAuthCodeRequest.setShareRatio(10);
>         try {
>             url = byteDanceOpenService.getByteDanceOpenV2ComponentService().getPreAuthUrl(url, getPreAuthCodeRequest);
>             // 添加来源，解决302跳转来源丢失的问题
>             response.addHeader("Referer", scheme + "://"+host);
>             response.sendRedirect(url);
>         } catch (ByteDanceErrorException | IOException e) {
>             log.error("gotoPreAuthUrl", e);
>             throw new RuntimeException(e);
>         }
>     }
> ```
> 
> https://partner.open-douyin.com/docs/resource/zh-CN/thirdparty/API/smallprogram/authorization/preauthcode 上面是demo 中的代码，但是查看了文档，发现参数是pre_auth_code_type app_name 这些，确定没搞错吗？还是抖音的接口变更了。

sdk里面是用的v1版本
![image](https://github.com/yydzxz/ByteDance-Open-Demo/assets/13087806/bbff11c5-da9e-4952-b294-d5e90eed1bbb)
![image](https://github.com/yydzxz/ByteDance-Open-Demo/assets/13087806/08a91a5a-0a3f-4369-b02e-d72e7063d80e)
现在抖音的文档是v2
![image](https://github.com/yydzxz/ByteDance-Open-Demo/assets/13087806/c8ebe1a5-6e07-4476-bbe2-3dc10fc52019)
